sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aspetter/react--test -f ./client/Dockerfile.dev ./client

script:
  - docker run aspetter/react-test npm test -- --coverage

after_success:
  - docker build -t aspetter/multi-client ./client
  - docker build -t aspetter/multi-nginx ./nginx
  - docker build -t aspetter/multi-server ./server
  - docker build -t aspetter/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aspetter/multi-client
  - docker push aspetter/multi-nginx
  - docker push aspetter/multi-server
  - docker push aspetter/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-2-050896652040
    bucket_path: dockerfile-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY